const AppStrings = {
  navLogoText: "Ocean Docs",
  navHome: "Home",
  navWaitlist: "Waitlist",
  navGitHub: "GitHub",

  heroTitle: "Ocean Documentation",
  heroSubtitle: "Ocean — The Native Platform for AI Agents",
  heroWaitlistCta: "Join the Waitlist",
  heroBetaNote: "Ocean is in private beta for macOS (Apple Silicon).",

  copyText: "Copy",
  copiedText: "Copied!",

  sidebarGettingStarted: "Getting Started",
  sidebarCoreFeatures: "Core Features",
  sidebarAiGit: "AI & Git",
  sidebarTools: "Tools",
  sidebarResources: "Resources",

  conceptTitle: "Core Concepts",
  conceptCowTitle: "Safe Exploration (COW)",
  conceptCowDesc: "Ocean uses Copy-On-Write isolation. Every session starts in a protected clone, allowing agents to experiment without risking your main branch until you decide to merge.",
  conceptAgentTitle: "Agent Awareness",
  conceptAgentDesc: "Ocean monitors AI agents in real-time. It tracks which files they touch, when they need input, and ensures their work is isolated from other active sessions.",

  configTitle: "Configuration",
  configEnvTitle: "Environment Variables",
  configAnthropicKey: "ANTHROPIC_API_KEY",
  configAnthropicDesc: "Enables AI-Assisted Merge and Claude-powered features.",

  proTipsTitle: "Pro Tips",
  tipRecoveryTitle: "Instant Recovery",
  tipRecoveryDesc: "If a session becomes unresponsive, hover over the tab in the sidebar and click the Refresh icon. Ocean will restart the shell while keeping your command history intact.",
  tipEnvTitle: "Custom Environments",
  tipEnvDesc: "Define per-workspace environment variables in a .ocean.env file. These are automatically loaded into every session within that workspace.",

  release0_15_0: "Persistent sessions, production Mastra evals, configured AI providers, release hardening",
  release0_13_2: "Key verification before build, fundraising memo, restoration of dev identifiers",
  release0_13_1: "Parallel Claudes: batch spawn, broadcast, N-way diff, promote winner, infra hardening",
  release0_13_0: "Save Session as Agent, Smollm plugin, software-review skill, workflow tool",
  release0_12_3: "WorkOS session cookie fixes, terminal resizing, PTY signal leak resolution",
  release0_11_0: "MCP Server Config Editor, persistent logs, port-forwarding dashboard",
  release0_10_1: "Git index lock fixes for parallel commits, Cursor CLI detection support",
  release0_10_0: "Multi-workspace dashboard, AI-assisted 3-way merge conflict visualizer",

  // Articles Strings
  articlesTitle: "Deep Dives &",
  articlesSubtitle: "Release Notes",
  articlesDesc: "Technical guides, architecture walkthroughs, and release notes for Ocean — The Native Platform for AI Agents.",
  sectionLatestRelease: "Latest Release",
  sectionGuidesByAudience: "Guides by Audience",
  footerText: "Ocean — The Native Platform for AI Agents",
};

const AppArticles = [
  {
    id: "parallel-agents-run-many-keep-the-best",
    tag: "Featured Guide",
    title: "Parallel Agents: Run Many, Keep the Best",
    desc: "Why, when, and how to run agents in parallel in Ocean — pros, cons, and the spawn → broadcast → N-way diff → promote-winner workflow, with screenshots.",
    date: "Featured",
  },
  {
    id: "gating-agent-workflows-with-mastra-evals",
    tag: "Featured Guide",
    title: "Don't Ship What You Can't Measure",
    desc: "Gate agentic workflows on Mastra-backed evals: score an agent's output and fail the run unless it clears a bar — with a worked faithfulness example.",
    date: "Featured",
  },
  {
    id: "ocean-v0-15-0-release",
    tag: "Release Notes",
    title: "What's New in Ocean v0.15.0",
    version: "0.15.0",
    desc: "Persistent sessions, production Mastra evals, configured AI providers, and release hardening.",
    date: "July 3, 2026",
  },
  {
    id: "ocean-v0-13-2-release",
    tag: "Release Notes",
    title: "What's New in Ocean v0.13.2",
    version: "0.13.2",
    desc: "Key verification before build, pre-seed investor memo, and parallel build plan enhancements.",
    date: "April 27, 2026",
  },
  {
    id: "ocean-v0-13-1-release",
    tag: "Release Notes",
    title: "What's New in Ocean v0.13.1",
    version: "0.13.1",
    desc: "Parallel Claudes features: batch spawn, broadcast, N-way diff, and promote winner.",
    date: "April 25, 2026",
  },
  {
    id: "ocean-v0-13-0-release",
    tag: "Release Notes",
    title: "What's New in Ocean v0.13.0",
    version: "0.13.0",
    desc: "Save Session as Agent, generic LLM chat panel, and software-review skill for codebase audits.",
    date: "April 20, 2026",
  },
  {
    id: "ocean-v0-12-3-release",
    tag: "Release Notes",
    title: "What's New in Ocean v0.12.3",
    version: "0.12.3",
    desc: "WorkOS session cookie fixes, improved terminal resizing, and PTY signal leak resolution.",
    date: "April 15, 2026",
  },
  {
    id: "ocean-v0-11-0-release",
    tag: "Release Notes",
    title: "What's New in Ocean v0.11.0",
    version: "0.11.0",
    desc: "MCP Server Config Editor, persistent session logs, and port-forwarding dashboard.",
    date: "April 10, 2026",
  },
  {
    id: "ocean-v0-10-1-release",
    tag: "Release Notes",
    title: "What's New in Ocean v0.10.1",
    version: "0.10.1",
    desc: "Git index lock fixes for parallel commits and Cursor CLI detection support.",
    date: "April 5, 2026",
  },
  {
    id: "ocean-v0-10-0-release",
    tag: "Release Notes",
    title: "What's New in Ocean v0.10.0",
    version: "0.10.0",
    desc: "Multi-workspace dashboard and advanced AI-assisted 3-way merge conflict visualizer.",
    date: "April 4, 2026",
  },
  {
    id: "ocean-v0-9-2-release",
    tag: "Release Notes",
    title: "What's New in Ocean v0.9.2",
    version: "0.9.2",
    desc: "Shell passthrough improvements, Ocean Agent API (MCP support), and critical security hardening.",
    date: "April 3, 2026",
  },
  {
    id: "ocean-v0-9-1-release",
    tag: "Release Notes",
    title: "What's New in Ocean v0.9.1",
    version: "0.9.1",
    desc: "New Claude OAuth usage panel and fixes for PTY deadlocks and OAuth poller guards.",
    date: "April 2, 2026",
  },
  {
    id: "ocean-v0-8-0-release",
    tag: "Release Notes",
    title: "What's New in Ocean v0.8.0",
    version: "0.8.0",
    desc: "Discard session changes, integrated file picker, and multiple git index auto-repair fixes.",
    date: "April 1, 2026",
  },
  {
    id: "ocean-v0-7-1-release",
    tag: "Release Notes",
    title: "What's New in Ocean v0.7.1",
    version: "0.7.1",
    desc: "Context menus, merge & ship workflow expansion, E2E test suite, Rust backend growth.",
    date: "March 25, 2026",
  },
  {
    id: "ocean-v0-7-0-release",
    tag: "Release Notes",
    title: "What's New in Ocean v0.7.0",
    version: "0.7.0",
    desc: "Conflict resolution, AI merge, file locks, stash, heatmap, and port forwarding.",
    date: "March 24, 2026",
  },
  {
    id: "ocean-v0-6-0-release",
    tag: "Release Notes",
    title: "What's New in Ocean v0.6.0",
    version: "0.6.0",
    desc: "Git Visualizer, split indicators, and 16 critical bug fixes.",
    date: "March 22, 2026",
  },
  {
    id: "ocean-for-ai-developers",
    tag: "Featured Guide",
    title: "Ocean for AI Developers",
    desc: "Deep dive into COW isolation, conflict detection, and optimizing your Claude context UI workflow.",
    date: "Featured",
  },
  {
    id: "ocean-for-architects",
    tag: "Architecture & Security",
    title: "Ocean for Architects",
    desc: "Explore the security model, system architecture, and performance budgets that drive Ocean.",
    date: "Technical",
  },
  {
    id: "ocean-for-product-managers",
    tag: "Business & ROI",
    title: "Ocean for Product Managers",
    desc: "Understand the business impact, team visibility benefits, and cost comparison for your organization.",
    date: "Strategy",
  },
  {
    id: "ocean-for-enterprises",
    tag: "Governance & Scale",
    title: "Ocean for Enterprises",
    desc: "Learn about audit trails, managed configurations, and the ROI framework for engineering leadership.",
    date: "Enterprise",
  },
];
